export const items = [
  {
    id: 1,
    name: '01',
    imageUrl: '/asset/details/shop/9hat/hat1/shop_hat1_ main_1.jpeg',
    price: '$195',
    description: 'A masterpiece of structural design, this sculpted felt cap redefines modern headwear. Its unique silhouette offers a bold statement while maintaining an air of understated elegance.',
    description_ko: '구조적 디자인의 걸작인 이 조각된 펠트 캡은 현대적인 모자를 재정의합니다. 독특한 실루엣은 절제된 우아함을 유지하면서도 대담한 표현을 제공합니다.',
    material: 'Material : 40% Suri Alpaca, 60% Wool\nLining : 100% Cotton',
    images: [
      '/asset/details/shop/9hat/hat1/shop_hat1_ main_1.jpeg',
      '/asset/details/shop/9hat/hat1/shop_hat1_ main2.jpeg',
      '/asset/details/shop/9hat/hat1/shop_hat1_sub1.jpg',
      '/asset/details/shop/9hat/hat1/shop_hat1_sub2.jpg',
      '/asset/details/shop/9hat/hat1/shop_hat1_lookbook1.jpeg',
      '/asset/details/shop/9hat/hat1/shop_hat1_lookbook2.jpg',
      '/asset/details/shop/9hat/hat1/shop_hat1_lookbook3.jpg',
    ]
  },
  {
    id: 2,
    name: '02',
    imageUrl: '/asset/details/shop/9hat/hat2/shop_hat2_main1 .jpeg',
    price: '$215',
    description: 'Breaking away from convention, this asymmetric brim hat features fluid lines and a dynamic form. Crafted for those who dare to stand out, it blends artistic vision with wearable fashion.',
    description_ko: '관습에서 벗어난 이 비대칭 챙 모자는 유동적인 라인과 역동적인 형태가 특징입니다. 남들과 다른 것을 추구하는 분들을 위해 제작되었으며, 예술적 비전과 웨어러블 패션을 조화시켰습니다.',
    material: 'Material : 40% Suri Alpaca, 60% Wool\nLining : 100% Cotton',
    images: [
      '/asset/details/shop/9hat/hat2/shop_hat2_main1 .jpeg',
      '/asset/details/shop/9hat/hat2/shop_hat2_main2.jpeg',
      '/asset/details/shop/9hat/hat2/shop_hat2_sub1.jpg',
      '/asset/details/shop/9hat/hat2/shop_hat2_sub2.jpg',
      '/asset/details/shop/9hat/hat2/shop_hat2_lookbook.jpg',
      '/asset/details/shop/9hat/hat2/shop_hat2_lookbook2.jpg',
    ]
  },
  {
    id: 3,
    name: '03',
    imageUrl: '/asset/details/shop/9hat/hat3/shop_hat3_main1.jpeg',
    price: '$220',
    description: 'A contemporary take on the classic beret, featuring structured wool that holds its shape perfectly. This piece combines traditional charm with architectural precision.',
    description_ko: '클래식 베레모를 현대적으로 재해석한 이 제품은 모양이 완벽하게 유지되는 구조적인 울이 특징입니다. 이 작품은 전통적인 매력과 건축적 정밀함을 결합했습니다.',
    material: 'Material : 40% Suri Alpaca, 60% Wool\nLining : 100% Cotton',
    images: [
      '/asset/details/shop/9hat/hat3/shop_hat3_main1.jpeg',
      '/asset/details/shop/9hat/hat3/shop_hat3_main2.jpeg',
      '/asset/details/shop/9hat/hat3/shop_hat3_main3.jpeg',
      '/asset/details/shop/9hat/hat3/shop_hat3_sub1.jpg',
      '/asset/details/shop/9hat/hat3/shop_hat3_sub2.jpg',
      '/asset/details/shop/9hat/hat3/shop_hat3_sub3.jpg',
      '/asset/details/shop/9hat/hat3/shop_hat3_lookbook1.jpg',
      '/asset/details/shop/9hat/hat3/shop_hat3_lookbook2.jpg',
    ]
  },
  {
    id: 4,
    name: '04',
    imageUrl: '/asset/details/shop/9hat/hat4/shop_hat4_main1.jpeg',
    price: '$420',
    description: 'Pushing the boundaries of design, this avant-garde headpiece is more than an accessory; it is wearable art. Intricate details and a striking profile make it the centerpiece of any ensemble.',
    description_ko: '디자인의 한계를 뛰어넘는 이 아방가르드 헤드피스는 액세서리 그 이상입니다. 착용 가능한 예술입니다. 복잡한 디테일과 눈에 띄는 프로필은 어떤 앙상블에서도 중심이 됩니다.',
    material: 'Material : 40% Suri Alpaca, 60% Wool\nLining : 100% Cotton',
    images: [
      '/asset/details/shop/9hat/hat4/shop_hat4_main1.jpeg',
      '/asset/details/shop/9hat/hat4/shop_hat4_main2.jpeg',
      '/asset/details/shop/9hat/hat4/shop_hat4_sub1.jpg',
      '/asset/details/shop/9hat/hat4/shop_hat4_sub2.jpg',
      '/asset/details/shop/9hat/hat4/shop_hat4_lookbook1.jpg',
      '/asset/details/shop/9hat/hat4/shop_hat4_lookbook2.jpg',
    ]
  },
  {
    id: 5,
    name: '05',
    imageUrl: '/asset/details/shop/9hat/hat5/shop_hat5_main2.jpeg',
    price: '$720',
    description: 'Rich in texture and depth, this layered hat explores the interplay of shadow and light. The meticulous construction creates a multi-dimensional look that is both intriguing and sophisticated.',
    description_ko: '질감과 깊이가 풍부한 이 레이어드 모자는 그림자와 빛의 상호 작용을 탐구합니다. 세심한 구조는 흥미롭고 세련된 다차원적인 룩을 연출합니다.',
    material: 'Material : 40% Suri Alpaca, 60% Wool\nLining : 100% Cotton',
    images: [
      '/asset/details/shop/9hat/hat5/shop_hat5_main2.jpeg',
      '/asset/details/shop/9hat/hat5/shop_hat5_main1.jpeg',
      '/asset/details/shop/9hat/hat5/shop_hat5_main3.jpeg',
      '/asset/details/shop/9hat/hat5/shop_hat5_sub1.jpg',
      '/asset/details/shop/9hat/hat5/shop_hat5_sub2.jpg',
      '/asset/details/shop/9hat/hat5/shop_hat5_sub3.jpg',
      '/asset/details/shop/9hat/hat5/shop_hat5_lookbook1.jpg',
      '/asset/details/shop/9hat/hat5/shop_hat5_lookbook2.jpg',
    ]
  },
  {
    id: 6,
    name: '06',
    imageUrl: '/asset/details/shop/9hat/hat6/shop_hat6_main1.jpeg',
    price: '$210',
    description: 'Elegant pleats meet structural design in this sophisticated headpiece. The fluid lines create a sense of movement, while the firm construction ensures a lasting impression.',
    description_ko: '우아한 주름과 구조적인 디자인이 만난 세련된 헤드피스입니다. 유려한 라인이 움직임을 만들어내며, 견고한 구조가 깊은 인상을 남깁니다.',
    material: 'Material : 40% Suri Alpaca, 60% Wool\nLining : 100% Cotton',
    images: [
      '/asset/details/shop/9hat/hat6/shop_hat6_main1.jpeg',
      '/asset/details/shop/9hat/hat6/shop_hat6_main2.jpeg',
      '/asset/details/shop/9hat/hat6/shop_hat6_sub1.jpg',
      '/asset/details/shop/9hat/hat6/shop_hat6_sub2.jpg',
      '/asset/details/shop/9hat/hat6/shop_hat6_lookbook1.jpg',
      '/asset/details/shop/9hat/hat6/shop_hat6_lookbook2.jpg',
    ]
  },
  {
    id: 7,
    name: '07',
    imageUrl: '/asset/details/shop/9hat/hat7/shop_hat7_main1.jpeg',
    price: '$205',
    description: 'Minimalist design with maximum impact. This hat features clean lines and a modern silhouette, perfect for those who appreciate understated luxury.',
    description_ko: '최대 효과를 내는 미니멀리스트 디자인. 깔끔한 라인과 현대적인 실루엣이 특징으로, 절제된 럭셔리를 선호하는 분들에게 완벽합니다.',
    material: 'Material : 40% Suri Alpaca, 60% Wool\nLining : 100% Cotton',
    images: [
      '/asset/details/shop/9hat/hat7/shop_hat7_main1.jpeg',
      '/asset/details/shop/9hat/hat7/shop_hat7_main2.jpeg',
      '/asset/details/shop/9hat/hat7/shop_hat7_main3.jpeg',
      '/asset/details/shop/9hat/hat7/shop_hat7_sub1.jpg',
      '/asset/details/shop/9hat/hat7/shop_hat7_sub2.jpg',
      '/asset/details/shop/9hat/hat7/shop_hat7_lookbook1.jpg',
      '/asset/details/shop/9hat/hat7/shop_hat7_lookbook2.jpg',
    ]
  },
  {
    id: 8,
    name: '08',
    imageUrl: '/asset/details/shop/9hat/hat8/shop_hat8_main1.jpeg',
    price: '$220',
    description: 'A fusion of texture and form, this unique piece challenges conventional headwear design. The interplay of materials creates a tactile experience.',
    description_ko: '질감과 형태의 융합, 이 독특한 작품은 기존의 모자 디자인에 도전합니다. 재료의 상호 작용은 촉각적인 경험을 선사합니다.',
    material: 'Material : 40% Suri Alpaca, 60% Wool\nLining : 100% Cotton',
    images: [
      '/asset/details/shop/9hat/hat8/shop_hat8_main1.jpeg',
      '/asset/details/shop/9hat/hat8/shop_hat8_main2.jpeg',
      '/asset/details/shop/9hat/hat8/shop_hat8_sub1.jpg',
      '/asset/details/shop/9hat/hat8/shop_hat8_sub2.jpg',
      '/asset/details/shop/9hat/hat8/shop_hat8_lookbook1.jpg',
    ]
  },
  {
    id: 9,
    name: '09',
    imageUrl: '/asset/details/shop/9hat/hat9/shop_hat9_main1.jpg',
    price: '$198',
    description: 'Bold and expressive, this hat is designed for the confident individual. Its striking shape and detailing command attention in any setting.',
    description_ko: '대담하고 표현력이 풍부한 이 모자는 자신감 있는 개인을 위해 디자인되었습니다. 눈에 띄는 모양과 디테일은 어떤 환경에서도 주목을 끕니다.',
    material: 'Material : 40% Suri Alpaca, 60% Wool\nLining : 100% Cotton',
    images: [
      '/asset/details/shop/9hat/hat9/shop_hat9_main1.jpg',
      '/asset/details/shop/9hat/hat9/shop_hat9_main2.jpeg',
      '/asset/details/shop/9hat/hat9/shop_hat9_main3.jpeg',
      '/asset/details/shop/9hat/hat9/shop_hat9_sub1.jpg',
      '/asset/details/shop/9hat/hat9/shop_hat9_sub2.jpg',
      '/asset/details/shop/9hat/hat9/shop_hat9_lookbook1.jpg',
      '/asset/details/shop/9hat/hat9/shop_hat9_lookbook2.jpg',
    ]
  }
];
